# Find more configuration details here
# https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md
# Config syntax for them here
# https://github.com/brigade/scss-lint/blob/master/config/default.yml
linters:
    Comment:
        enabled: true
        allowed: ""

    Indentation:
        enabled: true
        allow_non_nested_indentation: false
        character: space
        width: 4
        exclude:
          - 'sass/style.scss' # Stops force @import indentation (Note SBT scss-linter wont adhere to this)

    IdSelector:
        enabled: false

    DeclarationOrder:
        enabled: false

    VendorPrefix:
        enabled: false

    ImportantRule:
        enabled: false

    ColorVariable:
        enabled: false

    SelectorFormat:
        enabled: false

    SelectorDepth:
        max_depth: 5

    NestingDepth:
        max_depth: 5

    # Comments should all be // not /*
    Comment:
        enabled: false

    # Should we have 0.1 or .1
    LeadingZero:
        enabled: false

    # Properties should be sorted in order
    PropertySortOrder:
        enabled: false

    QualifyingElement:
        enabled: false
